/**
 * String templates for a generated **Python** MCP-server project.
 *
 * Mirrors the TypeScript emitter (`templates.ts`) one-for-one so behavior matches: low-level MCP
 * Python SDK, raw JSON-Schema tool inputs (no lossy conversion), env-based auth, stdlib `urllib`
 * for HTTP (the only third-party dependency is `mcp`). Spec-derived strings are JSON-encoded — a
 * JSON string literal is also a valid Python string literal — and comments are newline-stripped.
 */
import type { JsonSchema, SecurityScheme } from "../ir/model.js";
import { GENERATOR_NAME, GENERATOR_VERSION } from "../version.js";

const BANNER = `# Generated by ${GENERATOR_NAME} v${GENERATOR_VERSION}. Safe to edit.`;

/** A serializable tool record written to tools.json and loaded at runtime. */
export interface PyTool {
  name: string;
  description: string;
  inputSchema: JsonSchema;
  plan: unknown;
}

/** Collapse whitespace so a spec-derived value can't break out of a `#` comment. */
function commentSafe(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

/** Python package name: importable, lower_snake, never leading-digit. */
export function toPackageModule(serverName: string): string {
  let mod = serverName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  if (mod.length === 0) mod = "api_mcp";
  if (/^[0-9]/.test(mod)) mod = `pkg_${mod}`;
  return mod;
}

export function pyprojectToml(name: string, version: string, pkg: string): string {
  return [
    "[project]",
    `name = ${JSON.stringify(name)}`,
    `version = ${JSON.stringify(version)}`,
    'requires-python = ">=3.10"',
    'dependencies = ["mcp>=1.2.0", "anyio>=4.0"]',
    "",
    "[project.scripts]",
    `${name} = "${pkg}.__main__:run"`,
    "",
    "[build-system]",
    'requires = ["hatchling"]',
    'build-backend = "hatchling.build"',
    "",
    "[tool.hatch.build.targets.wheel]",
    `packages = ["${pkg}"]`,
    "",
  ].join("\n");
}

export function gitignorePy(): string {
  return ["__pycache__/", "*.pyc", ".venv/", ".env", "dist/", "*.egg-info/", ""].join("\n");
}

export function initPy(): string {
  return `${BANNER}\n"""Generated MCP server package."""\n`;
}

export function configPy(defaultBaseUrl: string): string {
  return [
    BANNER,
    "import os",
    "",
    `BASE_URL = os.environ.get("API_BASE_URL", ${JSON.stringify(defaultBaseUrl)})`,
    "",
  ].join("\n");
}

function authBlockPy(scheme: SecurityScheme): string[] {
  const lines: string[] = [];
  const label = commentSafe(
    `${scheme.name} (${scheme.type}${scheme.scheme ? "/" + scheme.scheme : ""})`,
  );
  lines.push(`    # ${label}`);
  lines.push(`    if ${JSON.stringify(scheme.name)} in security:`);
  if (scheme.type === "apiKey") {
    const env = scheme.envVars[0]!;
    const param = scheme.paramName ?? "X-API-Key";
    lines.push(`        value = os.environ.get(${JSON.stringify(env)})`);
    lines.push("        if value:");
    if (scheme.in === "query") {
      lines.push(`            query[${JSON.stringify(param)}] = value`);
    } else if (scheme.in === "cookie") {
      lines.push(
        `            headers["cookie"] = (headers["cookie"] + "; " if headers.get("cookie") else "") + ${JSON.stringify(
          param + "=",
        )} + value`,
      );
    } else {
      lines.push(`            headers[${JSON.stringify(param)}] = value`);
    }
  } else if (scheme.type === "http" && scheme.scheme?.toLowerCase() === "basic") {
    const [u, p] = scheme.envVars;
    lines.push(`        user = os.environ.get(${JSON.stringify(u)})`);
    lines.push(`        password = os.environ.get(${JSON.stringify(p)})`);
    lines.push("        if user and password:");
    lines.push('            token = base64.b64encode((user + ":" + password).encode()).decode()');
    lines.push('            headers["authorization"] = "Basic " + token');
  } else if (scheme.tokenUrl) {
    // oauth2 client-credentials: exchange a client id/secret for a bearer token.
    const [id, secret] = scheme.envVars;
    lines.push(`        client_id = os.environ.get(${JSON.stringify(id)})`);
    lines.push(`        client_secret = os.environ.get(${JSON.stringify(secret)})`);
    lines.push("        if client_id and client_secret:");
    lines.push(
      `            token = _get_token(${JSON.stringify(scheme.tokenUrl)}, client_id, client_secret)`,
    );
    lines.push('            headers["authorization"] = "Bearer " + token');
  } else {
    // http bearer, oauth2, openIdConnect -> pre-obtained token.
    const env = scheme.envVars[0]!;
    lines.push(`        value = os.environ.get(${JSON.stringify(env)})`);
    lines.push("        if value:");
    lines.push('            headers["authorization"] = "Bearer " + value');
  }
  return lines;
}

/** Emitted token fetch + cache, only when a client-credentials scheme is present. */
function oauthHelperPy(): string[] {
  return [
    "_token_cache = {}",
    "",
    "",
    "def _get_token(token_url, client_id, client_secret):",
    "    key = token_url + '|' + client_id",
    "    cached = _token_cache.get(key)",
    "    if cached and cached[1] > time.time():",
    "        return cached[0]",
    "    data = urllib.parse.urlencode(",
    '        {"grant_type": "client_credentials", "client_id": client_id, "client_secret": client_secret}',
    "    ).encode()",
    "    req = urllib.request.Request(",
    "        token_url,",
    "        data=data,",
    '        headers={"content-type": "application/x-www-form-urlencoded"},',
    '        method="POST",',
    "    )",
    "    with urllib.request.urlopen(req) as resp:",
    "        payload = json.loads(resp.read().decode())",
    '    token = payload.get("access_token")',
    "    if not token:",
    '        raise RuntimeError("OAuth token response had no access_token")',
    '    ttl = payload.get("expires_in", 3600)',
    "    _token_cache[key] = (token, time.time() + ttl - 30)",
    "    return token",
    "",
  ];
}

export function authPy(schemes: SecurityScheme[]): string {
  const body = schemes.flatMap(authBlockPy);
  const hasOAuth = schemes.some((s) => s.tokenUrl);
  const imports = hasOAuth
    ? [
        "import base64",
        "import json",
        "import os",
        "import time",
        "import urllib.parse",
        "import urllib.request",
      ]
    : ["import base64", "import os"];
  return [
    BANNER,
    ...imports,
    "",
    "",
    ...(hasOAuth ? oauthHelperPy() : []),
    ...(hasOAuth ? [""] : []),
    "def apply_auth(headers, query, security):",
    '    """Inject env-backed credentials. Secrets are never embedded."""',
    ...(body.length > 0
      ? body
      : ["    # No security schemes detected on the source API.", "    pass"]),
    "",
  ].join("\n");
}

export function httpClientPy(): string {
  return [
    BANNER,
    "import json",
    "import urllib.error",
    "import urllib.parse",
    "import urllib.request",
    "",
    "from .auth import apply_auth",
    "from .config import BASE_URL",
    "",
    "",
    "def call_operation(plan, args):",
    "    if not BASE_URL:",
    '        raise RuntimeError("API base URL is not set. Set API_BASE_URL in the environment.")',
    '    path = plan["pathTemplate"]',
    '    for name in plan["pathParams"]:',
    "        value = args.get(name)",
    '        encoded = urllib.parse.quote(str(value if value is not None else ""), safe="")',
    '        path = path.replace("{" + name + "}", encoded)',
    "    query = {}",
    '    for name in plan["queryParams"]:',
    "        value = args.get(name)",
    "        if value is not None:",
    "            query[name] = str(value)",
    "    headers = {}",
    '    for name in plan["headerParams"]:',
    "        value = args.get(name)",
    "        if value is not None:",
    "            headers[name] = str(value)",
    "    data = None",
    '    body_param = plan.get("bodyParam")',
    "    if body_param and args.get(body_param) is not None:",
    "        raw = args[body_param]",
    '        content_type = plan.get("contentType")',
    '        if content_type and "json" in content_type:',
    '            headers["content-type"] = "application/json"',
    "            data = json.dumps(raw).encode()",
    "        else:",
    "            if content_type:",
    '                headers["content-type"] = content_type',
    "            data = raw.encode() if isinstance(raw, str) else json.dumps(raw).encode()",
    '    apply_auth(headers, query, plan["security"])',
    '    url = BASE_URL.rstrip("/") + "/" + path.lstrip("/")',
    "    if query:",
    '        url += "?" + urllib.parse.urlencode(query)',
    '    request = urllib.request.Request(url, data=data, headers=headers, method=plan["method"])',
    "    try:",
    "        with urllib.request.urlopen(request) as response:",
    "            return response.read().decode()",
    "    except urllib.error.HTTPError as error:",
    "        detail = error.read().decode()[:800]",
    '        raise RuntimeError("HTTP " + str(error.code) + ": " + detail)',
    "",
  ].join("\n");
}

export function toolsPy(): string {
  return [
    BANNER,
    "import json",
    "import pathlib",
    "",
    'TOOLS = json.loads((pathlib.Path(__file__).parent / "tools.json").read_text())',
    "",
  ].join("\n");
}

export function serverPy(name: string): string {
  return [
    BANNER,
    "import mcp.types as types",
    "from mcp.server.lowlevel import Server",
    "",
    "from .http_client import call_operation",
    "from .tools import TOOLS",
    "",
    `server = Server(${JSON.stringify(name)})`,
    "",
    "",
    "@server.list_tools()",
    "async def list_tools():",
    "    return [",
    '        types.Tool(name=t["name"], description=t["description"], inputSchema=t["inputSchema"])',
    "        for t in TOOLS",
    "    ]",
    "",
    "",
    "@server.call_tool()",
    "async def call_tool(name, arguments):",
    '    tool = next((t for t in TOOLS if t["name"] == name), None)',
    "    if tool is None:",
    '        return [types.TextContent(type="text", text="Unknown tool: " + name)]',
    "    try:",
    '        text = call_operation(tool["plan"], arguments or {})',
    '        return [types.TextContent(type="text", text=text)]',
    "    except Exception as error:  # noqa: BLE001",
    '        return [types.TextContent(type="text", text="Error: " + str(error))]',
    "",
  ].join("\n");
}

export function mainPy(): string {
  return [
    BANNER,
    "import anyio",
    "from mcp.server.stdio import stdio_server",
    "",
    "from .server import server",
    "",
    "",
    "async def main():",
    "    async with stdio_server() as (read_stream, write_stream):",
    "        await server.run(read_stream, write_stream, server.create_initialization_options())",
    "",
    "",
    "def run():",
    "    anyio.run(main)",
    "",
    "",
    'if __name__ == "__main__":',
    "    run()",
    "",
  ].join("\n");
}

export function dockerfilePy(pkg: string): string {
  return [
    "FROM python:3.12-slim",
    "WORKDIR /app",
    "COPY . .",
    "RUN pip install --no-cache-dir .",
    `CMD ["python", "-m", "${pkg}"]`,
    "",
  ].join("\n");
}

export interface PyReadmeData {
  serverName: string;
  pkg: string;
  apiTitle: string;
  toolCount: number;
  schemes: SecurityScheme[];
}

export function readmePy(data: PyReadmeData): string {
  const envLines = data.schemes.flatMap((s) => s.envVars).map((v) => "- `" + v + "`");
  return [
    `# ${data.serverName}`,
    "",
    `A Python MCP server for **${data.apiTitle}**, generated by ${GENERATOR_NAME}.`,
    `It exposes ${data.toolCount} tool(s) that call the upstream API directly.`,
    "",
    "## Quickstart",
    "",
    "```bash",
    "python -m venv .venv && source .venv/bin/activate",
    "pip install -e .",
    "cp .env.example .env   # then fill in values",
    `python -m ${data.pkg}   # runs over stdio`,
    "```",
    "",
    "## Configuration",
    "",
    "- `API_BASE_URL` — base URL of the upstream API.",
    ...(envLines.length > 0 ? ["", "Credentials:", ...envLines] : []),
    "",
    "## Connecting a client",
    "",
    "```json",
    "{",
    '  "mcpServers": {',
    `    "${data.serverName}": {`,
    '      "command": "python",',
    `      "args": ["-m", "${data.pkg}"],`,
    '      "env": { "API_BASE_URL": "https://api.example.com" }',
    "    }",
    "  }",
    "}",
    "```",
    "",
  ].join("\n");
}
