/**
 * String templates for a generated **Python** MCP-server project.
 *
 * Mirrors the TypeScript emitter (`templates.ts`) one-for-one so behavior matches: low-level MCP
 * Python SDK, raw JSON-Schema tool inputs (no lossy conversion), env-based auth, stdlib `urllib`
 * for HTTP (the only third-party dependency is `mcp`). Spec-derived strings are JSON-encoded — a
 * JSON string literal is also a valid Python string literal — and comments are newline-stripped.
 */
import type { JsonSchema, SecurityScheme } from "../ir/model.js";
import type { EmitSource } from "./templates.js";
import { GENERATOR_NAME, GENERATOR_VERSION } from "../version.js";

const BANNER = `# Generated by ${GENERATOR_NAME} v${GENERATOR_VERSION}. Safe to edit.`;

/** A serializable tool record written to tools.json and loaded at runtime. */
export interface PyTool {
  name: string;
  description: string;
  inputSchema: JsonSchema;
  plan: unknown;
  /** Env namespace of the tool's source API; absent on legacy records (bare vars only). */
  sourceNamespace?: string;
}

/** Collapse whitespace so a spec-derived value can't break out of a `#` comment. */
function commentSafe(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

/** Python package name: importable, lower_snake, never leading-digit. */
export function toPackageModule(serverName: string): string {
  let mod = serverName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  if (mod.length === 0) mod = "api_mcp";
  if (/^[0-9]/.test(mod)) mod = `pkg_${mod}`;
  return mod;
}

export function pyprojectToml(
  name: string,
  version: string,
  pkg: string,
  variant: "lowlevel" | "fastmcp" = "lowlevel",
): string {
  const deps = variant === "fastmcp" ? '["fastmcp>=2,<3"]' : '["mcp>=1.2.0", "anyio>=4.0"]';
  return [
    "[project]",
    `name = ${JSON.stringify(name)}`,
    `version = ${JSON.stringify(version)}`,
    'requires-python = ">=3.10"',
    `dependencies = ${deps}`,
    "",
    "[project.scripts]",
    `${name} = "${pkg}.__main__:run"`,
    "",
    "[build-system]",
    'requires = ["hatchling"]',
    'build-backend = "hatchling.build"',
    "",
    "[tool.hatch.build.targets.wheel]",
    `packages = ["${pkg}"]`,
    "",
  ].join("\n");
}

export function gitignorePy(): string {
  return ["__pycache__/", "*.pyc", ".venv/", ".env", "dist/", "*.egg-info/", ""].join("\n");
}

export function initPy(): string {
  return `${BANNER}\n"""Generated MCP server package."""\n`;
}

export function configPy(defaultBaseUrl: string, sources: EmitSource[] = []): string {
  const sourceMap = Object.fromEntries(
    sources.filter((s) => s.baseUrl).map((s) => [s.namespace, s.baseUrl]),
  );
  return [
    BANNER,
    "import os",
    "",
    `DEFAULT_BASE_URL = ${JSON.stringify(defaultBaseUrl)}`,
    "",
    "# Default base URL per aggregated source API (env namespace -> the spec's first server).",
    `SOURCES = ${pyDict(sourceMap)}`,
    "",
    "",
    "def resolve_base_url(ns=None):",
    '    """<NS>_API_BASE_URL, then API_BASE_URL, then the source\'s server, then the default."""',
    "    if ns:",
    '        value = os.environ.get(ns + "_API_BASE_URL")',
    "        if value:",
    "            return value",
    '    return os.environ.get("API_BASE_URL") or (SOURCES.get(ns) if ns else None) or DEFAULT_BASE_URL',
    "",
    "",
    'BASE_URL = os.environ.get("API_BASE_URL", DEFAULT_BASE_URL)',
    "",
  ].join("\n");
}

/** Render a flat string->string map as a Python dict literal (JSON strings are valid Python). */
function pyDict(map: Record<string, string>): string {
  const entries = Object.entries(map);
  if (entries.length === 0) return "{}";
  return (
    "{\n" +
    entries.map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n") +
    "\n}"
  );
}

function authBlockPy(scheme: SecurityScheme): string[] {
  const lines: string[] = [];
  const label = commentSafe(
    `${scheme.name} (${scheme.type}${scheme.scheme ? "/" + scheme.scheme : ""})`,
  );
  lines.push(`    # ${label}`);
  lines.push(`    if ${JSON.stringify(scheme.name)} in security:`);
  if (scheme.type === "apiKey") {
    const env = scheme.envVars[0]!;
    const param = scheme.paramName ?? "X-API-Key";
    lines.push(`        value = _read_env(ns, ${JSON.stringify(env)})`);
    lines.push("        if value:");
    if (scheme.in === "query") {
      lines.push(`            query[${JSON.stringify(param)}] = value`);
    } else if (scheme.in === "cookie") {
      lines.push(
        `            headers["cookie"] = (headers["cookie"] + "; " if headers.get("cookie") else "") + ${JSON.stringify(
          param + "=",
        )} + value`,
      );
    } else {
      lines.push(`            headers[${JSON.stringify(param)}] = value`);
    }
  } else if (scheme.type === "http" && scheme.scheme?.toLowerCase() === "basic") {
    const [u, p] = scheme.envVars;
    lines.push(`        user = _read_env(ns, ${JSON.stringify(u)})`);
    lines.push(`        password = _read_env(ns, ${JSON.stringify(p)})`);
    lines.push("        if user and password:");
    lines.push('            token = base64.b64encode((user + ":" + password).encode()).decode()');
    lines.push('            headers["authorization"] = "Basic " + token');
  } else if (scheme.tokenUrl && scheme.grant === "refresh_token") {
    // oauth2 refresh-token grant: exchange a pre-obtained refresh token for access tokens; a
    // pre-obtained bearer in the trailing env var still works as a fallback.
    const [id, secret, refresh, fallback] = scheme.envVars;
    lines.push(`        client_id = _read_env(ns, ${JSON.stringify(id)})`);
    lines.push(`        client_secret = _read_env(ns, ${JSON.stringify(secret)})`);
    lines.push(`        refresh_token = _read_env(ns, ${JSON.stringify(refresh)})`);
    lines.push("        if client_id and refresh_token:");
    lines.push(
      `            token = _get_refresh_token(${JSON.stringify(scheme.tokenUrl)}, client_id, client_secret, refresh_token)`,
    );
    lines.push('            headers["authorization"] = "Bearer " + token');
    lines.push("        else:");
    lines.push(`            value = _read_env(ns, ${JSON.stringify(fallback)})`);
    lines.push("            if value:");
    lines.push('                headers["authorization"] = "Bearer " + value');
  } else if (scheme.tokenUrl) {
    // oauth2 client-credentials: exchange a client id/secret for a bearer token.
    const [id, secret] = scheme.envVars;
    lines.push(`        client_id = _read_env(ns, ${JSON.stringify(id)})`);
    lines.push(`        client_secret = _read_env(ns, ${JSON.stringify(secret)})`);
    lines.push("        if client_id and client_secret:");
    lines.push(
      `            token = _get_token(${JSON.stringify(scheme.tokenUrl)}, client_id, client_secret)`,
    );
    lines.push('            headers["authorization"] = "Bearer " + token');
  } else {
    // http bearer, oauth2, openIdConnect -> pre-obtained token.
    const env = scheme.envVars[0]!;
    lines.push(`        value = _read_env(ns, ${JSON.stringify(env)})`);
    lines.push("        if value:");
    lines.push('            headers["authorization"] = "Bearer " + value');
  }
  return lines;
}

/** Emitted client-credentials token fetch, only when such a scheme is present. */
function oauthCcHelperPy(): string[] {
  return [
    "def _get_token(token_url, client_id, client_secret):",
    "    key = token_url + '|' + client_id",
    "    cached = _token_cache.get(key)",
    "    if cached and cached[1] > time.time():",
    "        return cached[0]",
    "    data = urllib.parse.urlencode(",
    '        {"grant_type": "client_credentials", "client_id": client_id, "client_secret": client_secret}',
    "    ).encode()",
    "    req = urllib.request.Request(",
    "        token_url,",
    "        data=data,",
    '        headers={"content-type": "application/x-www-form-urlencoded"},',
    '        method="POST",',
    "    )",
    "    with urllib.request.urlopen(req) as resp:",
    "        payload = json.loads(resp.read().decode())",
    '    token = payload.get("access_token")',
    "    if not token:",
    '        raise RuntimeError("OAuth token response had no access_token")',
    '    ttl = payload.get("expires_in", 3600)',
    "    _token_cache[key] = (token, time.time() + ttl - 30)",
    "    return token",
    "",
  ];
}

/** Emitted refresh-token grant exchange, only when such a scheme is present. */
function oauthRefreshHelperPy(): string[] {
  return [
    "# Rotated refresh tokens live only in memory; re-supply via env after a restart if your",
    "# provider invalidates the old token on each exchange.",
    "_refresh_overrides = {}",
    "",
    "",
    "def _get_refresh_token(token_url, client_id, client_secret, refresh_token):",
    "    key = token_url + '|' + client_id + '|' + refresh_token",
    "    cached = _token_cache.get(key)",
    "    if cached and cached[1] > time.time():",
    "        return cached[0]",
    "    fields = {",
    '        "grant_type": "refresh_token",',
    '        "refresh_token": _refresh_overrides.get(key, refresh_token),',
    '        "client_id": client_id,',
    "    }",
    "    if client_secret:",
    '        fields["client_secret"] = client_secret',
    "    data = urllib.parse.urlencode(fields).encode()",
    "    req = urllib.request.Request(",
    "        token_url,",
    "        data=data,",
    '        headers={"content-type": "application/x-www-form-urlencoded"},',
    '        method="POST",',
    "    )",
    "    with urllib.request.urlopen(req) as resp:",
    "        payload = json.loads(resp.read().decode())",
    '    token = payload.get("access_token")',
    "    if not token:",
    '        raise RuntimeError("OAuth token response had no access_token")',
    '    if payload.get("refresh_token"):',
    '        _refresh_overrides[key] = payload["refresh_token"]',
    '    ttl = payload.get("expires_in", 3600)',
    "    _token_cache[key] = (token, time.time() + ttl - 30)",
    "    return token",
    "",
  ];
}

export function authPy(schemes: SecurityScheme[]): string {
  const body = schemes.flatMap(authBlockPy);
  const hasOAuth = schemes.some((s) => s.tokenUrl);
  const hasCc = schemes.some((s) => s.tokenUrl && s.grant !== "refresh_token");
  const hasRefresh = schemes.some((s) => s.tokenUrl && s.grant === "refresh_token");
  const helpers = hasOAuth
    ? [
        "_token_cache = {}",
        "",
        "",
        ...(hasCc ? oauthCcHelperPy() : []),
        ...(hasCc && hasRefresh ? [""] : []),
        ...(hasRefresh ? oauthRefreshHelperPy() : []),
      ]
    : [];
  const imports = hasOAuth
    ? [
        "import base64",
        "import json",
        "import os",
        "import time",
        "import urllib.parse",
        "import urllib.request",
      ]
    : ["import base64", "import os"];
  return [
    BANNER,
    ...imports,
    "",
    "",
    "def _read_env(ns, name):",
    '    """Namespaced env read: <NS>_<VAR> wins over the bare <VAR> for aggregated APIs."""',
    "    if ns:",
    '        value = os.environ.get(ns + "_" + name)',
    "        if value:",
    "            return value",
    "    return os.environ.get(name)",
    "",
    "",
    ...helpers,
    ...(hasOAuth ? [""] : []),
    "def apply_auth(headers, query, security, ns=None):",
    '    """Inject env-backed credentials. Secrets are never embedded."""',
    ...(body.length > 0
      ? body
      : ["    # No security schemes detected on the source API.", "    pass"]),
    "",
  ].join("\n");
}

/**
 * Emitted as `log.py` (not `logging.py`, which would shadow the stdlib module). Stdlib-only
 * structured logger mirroring the TypeScript `logger.ts`: JSON lines on stderr whose fields GCP
 * Cloud Logging and AWS CloudWatch parse natively, text on a TTY. Python's level names already
 * match GCP severities (DEBUG/INFO/WARNING/ERROR). `propagate = False` keeps FastMCP's own
 * logging configuration untouched and prevents double emission.
 */
export function logPy(): string {
  return [
    BANNER,
    '"""Structured logger: JSON lines on stderr in containers, text on a TTY.',
    "",
    "stdout is never used - it carries MCP JSON-RPC on the stdio transport.",
    "LOG_LEVEL=debug|info|warn|error (default info); LOG_FORMAT=json|text overrides detection.",
    'Pass context as logger.info("msg", extra={"ctx": {...}}); sensitive keys are redacted.',
    '"""',
    "import json",
    "import logging",
    "import os",
    "import sys",
    "import time",
    "",
    "_REDACTED_KEYS = {",
    '    "authorization",',
    '    "cookie",',
    '    "setcookie",',
    '    "token",',
    '    "refreshtoken",',
    '    "accesstoken",',
    '    "idtoken",',
    '    "secret",',
    '    "clientsecret",',
    '    "password",',
    '    "passwd",',
    '    "apikey",',
    '    "xapikey",',
    '    "credential",',
    '    "credentials",',
    "}",
    "",
    "_LEVELS = {",
    '    "debug": logging.DEBUG,',
    '    "info": logging.INFO,',
    '    "warn": logging.WARNING,',
    '    "error": logging.ERROR,',
    "}",
    "",
    "",
    "def _is_redacted(key):",
    '    return key.lower().replace("-", "").replace("_", "") in _REDACTED_KEYS',
    "",
    "",
    "def _scrub(fields, depth=0):",
    "    out = {}",
    "    for key, value in fields.items():",
    "        if _is_redacted(key):",
    '            out[key] = "[REDACTED]"',
    "        elif isinstance(value, dict) and depth < 4:",
    "            out[key] = _scrub(value, depth + 1)",
    "        else:",
    "            out[key] = value",
    "    return out",
    "",
    "",
    "def _rfc3339(record):",
    '    return time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime(record.created)) + ".%03dZ" % record.msecs',
    "",
    "",
    "class _JsonFormatter(logging.Formatter):",
    "    def format(self, record):",
    "        # Python level names match GCP Cloud Logging severities exactly.",
    "        entry = {",
    '            "severity": record.levelname,',
    '            "message": record.getMessage(),',
    '            "time": _rfc3339(record),',
    "        }",
    '        entry.update(_scrub(getattr(record, "ctx", None) or {}))',
    "        return json.dumps(entry, default=str)",
    "",
    "",
    "class _TextFormatter(logging.Formatter):",
    "    def format(self, record):",
    '        ctx = _scrub(getattr(record, "ctx", None) or {})',
    '        pairs = "".join(" %s=%s" % (k, v) for k, v in ctx.items())',
    '        clock = time.strftime("%H:%M:%S", time.gmtime(record.created))',
    '        return "%s %s %s%s" % (clock, record.levelname, record.getMessage(), pairs)',
    "",
    "",
    "def get_logger():",
    '    logger = logging.getLogger("mcp_server")',
    "    if logger.handlers:",
    "        return logger",
    "    handler = logging.StreamHandler(sys.stderr)",
    '    fmt = os.environ.get("LOG_FORMAT", "").lower()',
    '    use_json = fmt == "json" or (fmt != "text" and not sys.stderr.isatty())',
    "    handler.setFormatter(_JsonFormatter() if use_json else _TextFormatter())",
    "    logger.addHandler(handler)",
    '    logger.setLevel(_LEVELS.get(os.environ.get("LOG_LEVEL", "").lower(), logging.INFO))',
    "    # Keep this logger self-contained (FastMCP configures its own root handlers).",
    "    logger.propagate = False",
    "    return logger",
    "",
  ].join("\n");
}

export function httpClientPy(): string {
  return [
    BANNER,
    "import json",
    "import time",
    "import urllib.error",
    "import urllib.parse",
    "import urllib.request",
    "",
    "from .auth import apply_auth",
    "from .config import resolve_base_url",
    "from .log import get_logger",
    "",
    "logger = get_logger()",
    "",
    "",
    "def call_operation(plan, args, ns=None):",
    '    """`ns` scopes env lookups (base URL + credentials) to the tool\'s source API when',
    '    several APIs are aggregated; None (legacy tool records) means the bare vars."""',
    "    base_url = resolve_base_url(ns)",
    "    if not base_url:",
    '        raise RuntimeError("API base URL is not set. Set API_BASE_URL in the environment.")',
    '    path = plan["pathTemplate"]',
    '    for name in plan["pathParams"]:',
    "        value = args.get(name)",
    '        encoded = urllib.parse.quote(str(value if value is not None else ""), safe="")',
    '        path = path.replace("{" + name + "}", encoded)',
    "    query = {}",
    '    for name in plan["queryParams"]:',
    "        value = args.get(name)",
    "        if value is not None:",
    "            query[name] = str(value)",
    "    headers = {}",
    '    for name in plan["headerParams"]:',
    "        value = args.get(name)",
    "        if value is not None:",
    "            headers[name] = str(value)",
    "    data = None",
    '    body_param = plan.get("bodyParam")',
    "    if body_param and args.get(body_param) is not None:",
    "        raw = args[body_param]",
    '        content_type = plan.get("contentType")',
    '        if content_type and "json" in content_type:',
    '            headers["content-type"] = "application/json"',
    "            data = json.dumps(raw).encode()",
    "        else:",
    "            if content_type:",
    '                headers["content-type"] = content_type',
    "            data = raw.encode() if isinstance(raw, str) else json.dumps(raw).encode()",
    '    apply_auth(headers, query, plan["security"], ns)',
    '    url = base_url.rstrip("/") + "/" + path.lstrip("/")',
    "    # Query strings can carry apiKey credentials, headers always might - log neither.",
    "    safe_url = url",
    "    if query:",
    '        url += "?" + urllib.parse.urlencode(query)',
    '    request = urllib.request.Request(url, data=data, headers=headers, method=plan["method"])',
    "    start = time.monotonic()",
    "    try:",
    "        with urllib.request.urlopen(request) as response:",
    "            text = response.read().decode()",
    "        logger.debug(",
    '            "upstream response",',
    "            extra={",
    '                "ctx": {',
    '                    "method": plan["method"],',
    '                    "url": safe_url,',
    '                    "status": response.status,',
    '                    "duration_ms": int((time.monotonic() - start) * 1000),',
    "                }",
    "            },",
    "        )",
    "        return text",
    "    except urllib.error.HTTPError as error:",
    "        detail = error.read().decode()[:800]",
    "        logger.debug(",
    '            "upstream response",',
    "            extra={",
    '                "ctx": {',
    '                    "method": plan["method"],',
    '                    "url": safe_url,',
    '                    "status": error.code,',
    '                    "duration_ms": int((time.monotonic() - start) * 1000),',
    "                }",
    "            },",
    "        )",
    '        raise RuntimeError("HTTP " + str(error.code) + ": " + detail)',
    "",
  ].join("\n");
}

export function toolsPy(): string {
  return [
    BANNER,
    "import json",
    "import pathlib",
    "",
    'TOOLS = json.loads((pathlib.Path(__file__).parent / "tools.json").read_text())',
    "",
  ].join("\n");
}

export function serverPy(name: string): string {
  return [
    BANNER,
    "import time",
    "",
    "import mcp.types as types",
    "from mcp.server.lowlevel import Server",
    "",
    "from .http_client import call_operation",
    "from .log import get_logger",
    "from .tools import TOOLS",
    "",
    "logger = get_logger()",
    `server = Server(${JSON.stringify(name)})`,
    "",
    "",
    "@server.list_tools()",
    "async def list_tools():",
    "    return [",
    '        types.Tool(name=t["name"], description=t["description"], inputSchema=t["inputSchema"])',
    "        for t in TOOLS",
    "    ]",
    "",
    "",
    "@server.call_tool()",
    "async def call_tool(name, arguments):",
    '    tool = next((t for t in TOOLS if t["name"] == name), None)',
    "    if tool is None:",
    '        logger.warning("unknown tool requested", extra={"ctx": {"tool": name}})',
    '        return [types.TextContent(type="text", text="Unknown tool: " + name)]',
    "    start = time.monotonic()",
    "    try:",
    '        text = call_operation(tool["plan"], arguments or {}, tool.get("sourceNamespace"))',
    "        logger.debug(",
    '            "tool call ok",',
    '            extra={"ctx": {"tool": name, "duration_ms": int((time.monotonic() - start) * 1000)}},',
    "        )",
    '        return [types.TextContent(type="text", text=text)]',
    "    except Exception as error:  # noqa: BLE001",
    "        logger.warning(",
    '            "tool call failed",',
    "            extra={",
    '                "ctx": {',
    '                    "tool": name,',
    '                    "duration_ms": int((time.monotonic() - start) * 1000),',
    '                    "error": str(error),',
    "                }",
    "            },",
    "        )",
    '        return [types.TextContent(type="text", text="Error: " + str(error))]',
    "",
  ].join("\n");
}

/**
 * FastMCP-flavored server (opt-in): registers each tool as a `Tool` subclass carrying the raw
 * JSON-Schema input verbatim (`parameters=`), never FastMCP's type-hint schema derivation — the
 * no-lossy-round-trip invariant holds for both flavors.
 */
export function serverFastmcpPy(name: string): string {
  return [
    BANNER,
    "import time",
    "",
    "import mcp.types as types",
    "from fastmcp import FastMCP",
    "from fastmcp.tools import Tool",
    "from fastmcp.tools.tool import ToolResult",
    "",
    "from .http_client import call_operation",
    "from .log import get_logger",
    "from .tools import TOOLS",
    "",
    "logger = get_logger()",
    `server = FastMCP(${JSON.stringify(name)})`,
    "",
    "",
    "class _ApiTool(Tool):",
    '    """One upstream operation; its raw JSON-Schema input is served verbatim."""',
    "",
    "    record: dict",
    "",
    "    async def run(self, arguments):",
    "        start = time.monotonic()",
    "        try:",
    "            text = call_operation(",
    '                self.record["plan"], arguments or {}, self.record.get("sourceNamespace")',
    "            )",
    "            logger.debug(",
    '                "tool call ok",',
    "                extra={",
    '                    "ctx": {',
    '                        "tool": self.name,',
    '                        "duration_ms": int((time.monotonic() - start) * 1000),',
    "                    }",
    "                },",
    "            )",
    '            content = [types.TextContent(type="text", text=text)]',
    "        except Exception as error:  # noqa: BLE001",
    "            logger.warning(",
    '                "tool call failed",',
    "                extra={",
    '                    "ctx": {',
    '                        "tool": self.name,',
    '                        "duration_ms": int((time.monotonic() - start) * 1000),',
    '                        "error": str(error),',
    "                    }",
    "                },",
    "            )",
    '            content = [types.TextContent(type="text", text="Error: " + str(error))]',
    "        return ToolResult(content=content)",
    "",
    "",
    "for _tool in TOOLS:",
    "    server.add_tool(",
    "        _ApiTool(",
    '            name=_tool["name"],',
    '            description=_tool["description"],',
    '            parameters=_tool["inputSchema"],',
    "            record=_tool,",
    "        )",
    "    )",
    "",
  ].join("\n");
}

export function mainFastmcpPy(name: string): string {
  return [
    BANNER,
    "from .log import get_logger",
    "from .server import server",
    "",
    "",
    "def run():",
    `    get_logger().info(${JSON.stringify(name + " MCP server running on stdio")})`,
    "    server.run()  # stdio by default",
    "",
    "",
    'if __name__ == "__main__":',
    "    run()",
    "",
  ].join("\n");
}

export function mainPy(name: string): string {
  return [
    BANNER,
    "import anyio",
    "from mcp.server.stdio import stdio_server",
    "",
    "from .log import get_logger",
    "from .server import server",
    "",
    "",
    "async def main():",
    "    async with stdio_server() as (read_stream, write_stream):",
    `        get_logger().info(${JSON.stringify(name + " MCP server running on stdio")})`,
    "        await server.run(read_stream, write_stream, server.create_initialization_options())",
    "",
    "",
    "def run():",
    "    anyio.run(main)",
    "",
    "",
    'if __name__ == "__main__":',
    "    run()",
    "",
  ].join("\n");
}

export function dockerfilePy(pkg: string): string {
  return [
    "FROM python:3.12-slim",
    "WORKDIR /app",
    "COPY . .",
    "RUN pip install --no-cache-dir .",
    `CMD ["python", "-m", "${pkg}"]`,
    "",
  ].join("\n");
}

export interface PyReadmeData {
  serverName: string;
  pkg: string;
  apiTitle: string;
  toolCount: number;
  schemes: SecurityScheme[];
}

export function readmePy(data: PyReadmeData): string {
  const envLines = data.schemes.flatMap((s) => s.envVars).map((v) => "- `" + v + "`");
  return [
    `# ${data.serverName}`,
    "",
    `A Python MCP server for **${data.apiTitle}**, generated by ${GENERATOR_NAME}.`,
    `It exposes ${data.toolCount} tool(s) that call the upstream API directly.`,
    "",
    "## Quickstart",
    "",
    "```bash",
    "python -m venv .venv && source .venv/bin/activate",
    "pip install -e .",
    "cp .env.example .env   # then fill in values",
    `python -m ${data.pkg}   # runs over stdio`,
    "```",
    "",
    "## Configuration",
    "",
    "- `API_BASE_URL` — base URL of the upstream API.",
    ...(envLines.length > 0 ? ["", "Credentials:", ...envLines] : []),
    "",
    "When this server aggregates several APIs, each one also reads namespaced overrides —",
    "`<NAMESPACE>_API_BASE_URL` and `<NAMESPACE>_<VAR>` win over the bare variables for that",
    "API's tools (see `.env.example` for the exact names).",
    "",
    "## Logging",
    "",
    "Structured logs go to stderr (stdout carries the MCP protocol): JSON lines in containers,",
    "text on a TTY. Tune with `LOG_LEVEL=debug|info|warn|error` and `LOG_FORMAT=json|text` —",
    "the JSON fields (`severity`, `message`, `time`) are parsed natively by GCP Cloud Logging",
    "and AWS CloudWatch.",
    "",
    "## Connecting a client",
    "",
    "```json",
    "{",
    '  "mcpServers": {',
    `    "${data.serverName}": {`,
    '      "command": "python",',
    `      "args": ["-m", "${data.pkg}"],`,
    '      "env": { "API_BASE_URL": "https://api.example.com" }',
    "    }",
    "  }",
    "}",
    "```",
    "",
  ].join("\n");
}
