/**
 * String templates for every file in a generated MCP-server project.
 *
 * Generated TypeScript deliberately uses double-quoted strings and avoids template literals so
 * these host-side templates don't have to escape nested backticks/`${}`. Multi-line docs (README,
 * client config) are built from arrays of lines for the same reason.
 */
import type { JsonSchema, SecurityScheme } from "../ir/model.js";
import { GENERATOR_NAME, GENERATOR_VERSION } from "../version.js";

export type Transport = "stdio" | "http" | "both";

export interface RequestPlanData {
  method: string;
  pathTemplate: string;
  pathParams: string[];
  queryParams: string[];
  headerParams: string[];
  cookieParams: string[];
  bodyParam: string | null;
  contentType: string | null;
  security: string[];
}

export interface ToolEmit {
  name: string;
  method: string;
  path: string;
  description: string;
  /** One-line summary for the tool catalog (spec summary, or "METHOD /path"). */
  summary: string;
  /** Spec tags, surfaced in the tool catalog so a discovery layer can group/rank. */
  tags: string[];
  inputSchema: JsonSchema;
  plan: RequestPlanData;
  sourceTitle: string;
}

const GENERATED_BANNER = `// Generated by ${GENERATOR_NAME} v${GENERATOR_VERSION}. Safe to edit: tool files are\n// preserved on re-generation/append unless --force is used.`;

export function packageJson(name: string, version: string, transport: Transport): string {
  const scripts: Record<string, string> = {
    build: "tsc",
    start: "node dist/index.js",
  };
  if (transport === "http" || transport === "both") {
    scripts["start:http"] = "node dist/index.http.js";
  }
  const pkg = {
    name,
    version,
    private: true,
    type: "module",
    bin: { [name]: "dist/index.js" },
    scripts,
    dependencies: { "@modelcontextprotocol/sdk": "^1.29.0" },
    devDependencies: { typescript: "^5.6.0", "@types/node": "^22.0.0" },
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}

export function tsconfigJson(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          lib: ["ES2022"],
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          outDir: "dist",
          rootDir: "src",
          declaration: false,
          sourceMap: true,
        },
        include: ["src"],
      },
      null,
      2,
    ) + "\n"
  );
}

export function gitignore(): string {
  return ["node_modules/", "dist/", ".env", "*.log", ""].join("\n");
}

export function typesTs(): string {
  return [
    GENERATED_BANNER,
    "",
    "export interface ToolDef {",
    "  name: string;",
    "  description: string;",
    "  inputSchema: Record<string, unknown>;",
    "  handler: (args: Record<string, unknown>) => Promise<string>;",
    "}",
    "",
  ].join("\n");
}

export function configTs(defaultBaseUrl: string): string {
  return [
    GENERATED_BANNER,
    "",
    "export const config = {",
    `  baseUrl: process.env.API_BASE_URL ?? ${JSON.stringify(defaultBaseUrl)},`,
    "};",
    "",
  ].join("\n");
}

/** Collapse whitespace/newlines so a spec-derived value can't break out of a `//` comment. */
function commentSafe(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function authBlock(scheme: SecurityScheme): string[] {
  const lines: string[] = [];
  const guard = `  if (security.includes(${JSON.stringify(scheme.name)})) {`;
  const label = commentSafe(
    `${scheme.name} (${scheme.type}${scheme.scheme ? "/" + scheme.scheme : ""})`,
  );
  lines.push(`  // ${label}`);
  lines.push(guard);
  if (scheme.type === "apiKey") {
    const env = scheme.envVars[0]!;
    const param = scheme.paramName ?? "X-API-Key";
    lines.push(`    const value = process.env[${JSON.stringify(env)}];`);
    lines.push("    if (value) {");
    if (scheme.in === "query") {
      lines.push(`      url.searchParams.set(${JSON.stringify(param)}, value);`);
    } else if (scheme.in === "cookie") {
      lines.push(
        `      headers["cookie"] = (headers["cookie"] ? headers["cookie"] + "; " : "") + ${JSON.stringify(
          param + "=",
        )} + value;`,
      );
    } else {
      lines.push(`      headers[${JSON.stringify(param)}] = value;`);
    }
    lines.push("    }");
  } else if (scheme.type === "http" && scheme.scheme?.toLowerCase() === "basic") {
    const [u, p] = scheme.envVars;
    lines.push(`    const user = process.env[${JSON.stringify(u)}];`);
    lines.push(`    const pass = process.env[${JSON.stringify(p)}];`);
    lines.push("    if (user && pass) {");
    lines.push(
      '      headers["authorization"] = "Basic " + Buffer.from(user + ":" + pass).toString("base64");',
    );
    lines.push("    }");
  } else if (scheme.tokenUrl && scheme.grant === "refresh_token") {
    // oauth2 refresh-token grant: exchange a pre-obtained refresh token for access tokens; a
    // pre-obtained bearer in the trailing env var still works as a fallback.
    const [id, secret, refresh, fallback] = scheme.envVars;
    lines.push(`    const clientId = process.env[${JSON.stringify(id)}];`);
    lines.push(`    const clientSecret = process.env[${JSON.stringify(secret)}];`);
    lines.push(`    const refreshToken = process.env[${JSON.stringify(refresh)}];`);
    lines.push("    if (clientId && refreshToken) {");
    lines.push(
      `      const token = await getRefreshGrantToken(${JSON.stringify(scheme.tokenUrl)}, clientId, clientSecret, refreshToken);`,
    );
    lines.push('      headers["authorization"] = "Bearer " + token;');
    lines.push("    } else {");
    lines.push(`      const value = process.env[${JSON.stringify(fallback)}];`);
    lines.push('      if (value) headers["authorization"] = "Bearer " + value;');
    lines.push("    }");
  } else if (scheme.tokenUrl) {
    // oauth2 client-credentials: exchange a client id/secret for a bearer token.
    const [id, secret] = scheme.envVars;
    lines.push(`    const clientId = process.env[${JSON.stringify(id)}];`);
    lines.push(`    const clientSecret = process.env[${JSON.stringify(secret)}];`);
    lines.push("    if (clientId && clientSecret) {");
    lines.push(
      `      const token = await getClientCredentialsToken(${JSON.stringify(scheme.tokenUrl)}, clientId, clientSecret);`,
    );
    lines.push('      headers["authorization"] = "Bearer " + token;');
    lines.push("    }");
  } else {
    // http bearer, oauth2, openIdConnect -> pre-obtained token.
    const env = scheme.envVars[0]!;
    lines.push(`    const value = process.env[${JSON.stringify(env)}];`);
    lines.push('    if (value) headers["authorization"] = "Bearer " + value;');
  }
  lines.push("  }");
  return lines;
}

/** Emitted client-credentials token fetch, only when such a scheme is present. */
function oauthCcHelperTs(): string[] {
  return [
    "async function getClientCredentialsToken(",
    "  tokenUrl: string,",
    "  clientId: string,",
    "  clientSecret: string,",
    "): Promise<string> {",
    '    const key = tokenUrl + "|" + clientId;',
    "    const hit = _tokenCache.get(key);",
    "    if (hit && hit.expiresAt > Date.now()) return hit.token;",
    "    const body = new URLSearchParams({",
    '      grant_type: "client_credentials",',
    "      client_id: clientId,",
    "      client_secret: clientSecret,",
    "    }).toString();",
    "    const res = await fetch(tokenUrl, {",
    '      method: "POST",',
    '      headers: { "content-type": "application/x-www-form-urlencoded" },',
    "      body,",
    "    });",
    "    const text = await res.text();",
    "    if (!res.ok)",
    '      throw new Error("OAuth token request failed: HTTP " + res.status + " " + text.slice(0, 300));',
    "    const json = JSON.parse(text) as { access_token?: string; expires_in?: number };",
    '    if (!json.access_token) throw new Error("OAuth token response had no access_token");',
    '    const ttl = typeof json.expires_in === "number" ? json.expires_in : 3600;',
    "    _tokenCache.set(key, { token: json.access_token, expiresAt: Date.now() + ttl * 1000 - 30000 });",
    "    return json.access_token;",
    "}",
    "",
  ];
}

/** Emitted refresh-token grant exchange, only when such a scheme is present. */
function oauthRefreshHelperTs(): string[] {
  return [
    "// Rotated refresh tokens live only in memory; re-supply via env after a restart if your",
    "// provider invalidates the old token on each exchange.",
    "const _refreshOverrides = new Map<string, string>();",
    "",
    "async function getRefreshGrantToken(",
    "  tokenUrl: string,",
    "  clientId: string,",
    "  clientSecret: string | undefined,",
    "  refreshToken: string,",
    "): Promise<string> {",
    '    const key = tokenUrl + "|" + clientId + "|" + refreshToken;',
    "    const hit = _tokenCache.get(key);",
    "    if (hit && hit.expiresAt > Date.now()) return hit.token;",
    "    const fields: Record<string, string> = {",
    '      grant_type: "refresh_token",',
    "      refresh_token: _refreshOverrides.get(key) ?? refreshToken,",
    "      client_id: clientId,",
    "    };",
    "    if (clientSecret) fields.client_secret = clientSecret;",
    "    const body = new URLSearchParams(fields).toString();",
    "    const res = await fetch(tokenUrl, {",
    '      method: "POST",',
    '      headers: { "content-type": "application/x-www-form-urlencoded" },',
    "      body,",
    "    });",
    "    const text = await res.text();",
    "    if (!res.ok)",
    '      throw new Error("OAuth token request failed: HTTP " + res.status + " " + text.slice(0, 300));',
    "    const json = JSON.parse(text) as {",
    "      access_token?: string;",
    "      expires_in?: number;",
    "      refresh_token?: string;",
    "    };",
    '    if (!json.access_token) throw new Error("OAuth token response had no access_token");',
    "    if (json.refresh_token) _refreshOverrides.set(key, json.refresh_token);",
    '    const ttl = typeof json.expires_in === "number" ? json.expires_in : 3600;',
    "    _tokenCache.set(key, { token: json.access_token, expiresAt: Date.now() + ttl * 1000 - 30000 });",
    "    return json.access_token;",
    "}",
    "",
  ];
}

export function authTs(schemes: SecurityScheme[]): string {
  const body = schemes.flatMap(authBlock);
  const hasOAuth = schemes.some((s) => s.tokenUrl);
  const hasCc = schemes.some((s) => s.tokenUrl && s.grant !== "refresh_token");
  const hasRefresh = schemes.some((s) => s.tokenUrl && s.grant === "refresh_token");
  const helpers = hasOAuth
    ? [
        "const _tokenCache = new Map<string, { token: string; expiresAt: number }>();",
        "",
        ...(hasCc ? oauthCcHelperTs() : []),
        ...(hasRefresh ? oauthRefreshHelperTs() : []),
      ]
    : [];
  const signature = hasOAuth
    ? [
        "export async function applyAuth(",
        "  headers: Record<string, string>,",
        "  url: URL,",
        "  security: string[],",
        "): Promise<void> {",
      ]
    : [
        "export function applyAuth(",
        "  headers: Record<string, string>,",
        "  url: URL,",
        "  security: string[],",
        "): void {",
      ];
  return [
    GENERATED_BANNER,
    "",
    "// Injects credentials read from the environment. Secrets are never embedded.",
    ...helpers,
    ...signature,
    ...(body.length > 0 ? body : ["  // No security schemes detected on the source API."]),
    "}",
    "",
  ].join("\n");
}

export function httpClientTs(): string {
  return [
    GENERATED_BANNER,
    "",
    'import { config } from "../config.js";',
    'import { applyAuth } from "../auth.js";',
    "",
    "export interface RequestPlan {",
    "  method: string;",
    "  pathTemplate: string;",
    "  pathParams: string[];",
    "  queryParams: string[];",
    "  headerParams: string[];",
    "  cookieParams: string[];",
    "  bodyParam: string | null;",
    "  contentType: string | null;",
    "  security: string[];",
    "}",
    "",
    "function joinUrl(base: string, path: string): string {",
    '  if (!base) throw new Error("API base URL is not set. Set API_BASE_URL in the environment.");',
    '  return base.replace(/\\/+$/, "") + "/" + path.replace(/^\\/+/, "");',
    "}",
    "",
    "export async function callOperation(",
    "  plan: RequestPlan,",
    "  args: Record<string, unknown>,",
    "): Promise<string> {",
    "  let path = plan.pathTemplate;",
    "  for (const name of plan.pathParams) {",
    "    const value = args[name];",
    '    path = path.split("{" + name + "}").join(encodeURIComponent(String(value ?? "")));',
    "  }",
    "  const url = new URL(joinUrl(config.baseUrl, path));",
    "  for (const name of plan.queryParams) {",
    "    const value = args[name];",
    "    if (value === undefined || value === null) continue;",
    "    // Array query values are repeated (?k=1&k=2), the OpenAPI default (form/explode).",
    "    if (Array.isArray(value)) {",
    "      for (const v of value) {",
    "        if (v !== undefined && v !== null) url.searchParams.append(name, String(v));",
    "      }",
    "    } else {",
    "      url.searchParams.set(name, String(value));",
    "    }",
    "  }",
    "  const headers: Record<string, string> = {};",
    "  for (const name of plan.headerParams) {",
    "    const value = args[name];",
    "    if (value === undefined || value === null) continue;",
    '    headers[name] = Array.isArray(value) ? value.map(String).join(",") : String(value);',
    "  }",
    "  const cookies: string[] = [];",
    "  for (const name of plan.cookieParams) {",
    "    const value = args[name];",
    "    if (value !== undefined && value !== null) {",
    '      cookies.push(name + "=" + encodeURIComponent(String(value)));',
    "    }",
    "  }",
    "  if (cookies.length > 0) {",
    '    headers["cookie"] = (headers["cookie"] ? headers["cookie"] + "; " : "") + cookies.join("; ");',
    "  }",
    "  let body: string | undefined;",
    "  if (plan.bodyParam && args[plan.bodyParam] !== undefined) {",
    "    const raw = args[plan.bodyParam];",
    '    if (plan.contentType && plan.contentType.indexOf("json") >= 0) {',
    '      headers["content-type"] = "application/json";',
    "      body = JSON.stringify(raw);",
    "    } else {",
    '      if (plan.contentType) headers["content-type"] = plan.contentType;',
    '      body = typeof raw === "string" ? raw : JSON.stringify(raw);',
    "    }",
    "  }",
    "  await applyAuth(headers, url, plan.security);",
    "  const response = await fetch(url, { method: plan.method, headers, body });",
    "  const text = await response.text();",
    "  if (!response.ok) {",
    '    throw new Error("HTTP " + response.status + " " + response.statusText + ": " + text.slice(0, 800));',
    "  }",
    "  return text;",
    "}",
    "",
  ].join("\n");
}

export function toolFileTs(tool: ToolEmit): string {
  return [
    GENERATED_BANNER,
    "",
    'import type { ToolDef } from "../types.js";',
    'import { callOperation } from "../http/client.js";',
    "",
    `const inputSchema = ${JSON.stringify(tool.inputSchema, null, 2)} as Record<string, unknown>;`,
    "",
    `const plan = ${JSON.stringify(tool.plan, null, 2)};`,
    "",
    `export const ${tool.name}: ToolDef = {`,
    `  name: ${JSON.stringify(tool.name)},`,
    `  description: ${JSON.stringify(tool.description)},`,
    "  inputSchema,",
    "  handler: (args) => callOperation(plan, args),",
    "};",
    "",
  ].join("\n");
}

export function toolsIndexTs(toolNames: string[]): string {
  const imports = toolNames.map((n) => `import { ${n} } from "./${n}.js";`);
  return [
    GENERATED_BANNER,
    "",
    'import type { ToolDef } from "../types.js";',
    ...imports,
    "",
    `export const tools: ToolDef[] = [${toolNames.join(", ")}];`,
    "",
  ].join("\n");
}

export function serverTs(name: string, version: string): string {
  return [
    GENERATED_BANNER,
    "",
    'import { Server } from "@modelcontextprotocol/sdk/server/index.js";',
    "import {",
    "  ListToolsRequestSchema,",
    "  CallToolRequestSchema,",
    '} from "@modelcontextprotocol/sdk/types.js";',
    'import { tools } from "./tools/index.js";',
    "",
    "export function createServer(): Server {",
    "  const server = new Server(",
    `    { name: ${JSON.stringify(name)}, version: ${JSON.stringify(version)} },`,
    "    { capabilities: { tools: {} } },",
    "  );",
    "",
    "  server.setRequestHandler(ListToolsRequestSchema, async () => ({",
    "    tools: tools.map((t) => ({",
    "      name: t.name,",
    "      description: t.description,",
    "      inputSchema: t.inputSchema,",
    "    })),",
    "  }));",
    "",
    "  server.setRequestHandler(CallToolRequestSchema, async (request) => {",
    "    const tool = tools.find((t) => t.name === request.params.name);",
    "    if (!tool) {",
    "      return {",
    '        content: [{ type: "text", text: "Unknown tool: " + request.params.name }],',
    "        isError: true,",
    "      };",
    "    }",
    "    try {",
    "      const text = await tool.handler(",
    "        (request.params.arguments ?? {}) as Record<string, unknown>,",
    "      );",
    '      return { content: [{ type: "text", text }] };',
    "    } catch (err) {",
    "      return {",
    '        content: [{ type: "text", text: "Error: " + (err instanceof Error ? err.message : String(err)) }],',
    "        isError: true,",
    "      };",
    "    }",
    "  });",
    "",
    "  return server;",
    "}",
    "",
  ].join("\n");
}

export function indexStdioTs(name: string): string {
  return [
    GENERATED_BANNER,
    "",
    'import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";',
    'import { createServer } from "./server.js";',
    "",
    "async function main(): Promise<void> {",
    "  const server = createServer();",
    "  const transport = new StdioServerTransport();",
    "  await server.connect(transport);",
    `  console.error(${JSON.stringify(name + " MCP server running on stdio")});`,
    "}",
    "",
    "main().catch((err) => {",
    "  console.error(err);",
    "  process.exit(1);",
    "});",
    "",
  ].join("\n");
}

export function indexHttpTs(name: string): string {
  return [
    GENERATED_BANNER,
    "",
    'import { createServer as createHttpServer } from "node:http";',
    'import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";',
    'import { createServer } from "./server.js";',
    "",
    "const port = Number(process.env.PORT ?? 3000);",
    "",
    "// DNS-rebinding protection: only accept requests whose Host header is in this allowlist, so a",
    "// malicious web page cannot rebind to localhost and drive this server. Override for non-local",
    "// deployments via MCP_ALLOWED_HOSTS (comma-separated host[:port] values).",
    'const defaultHosts = "127.0.0.1:" + port + ",localhost:" + port;',
    "const allowedHostList = (process.env.MCP_ALLOWED_HOSTS ?? defaultHosts)",
    '  .split(",")',
    "  .map((h) => h.trim())",
    "  .filter(Boolean);",
    "",
    "// Stateless Streamable HTTP: a fresh server+transport per request.",
    "createHttpServer(async (req, res) => {",
    '  if (!req.url || !req.url.startsWith("/mcp")) {',
    "    res.statusCode = 404;",
    '    res.end("Not found");',
    "    return;",
    "  }",
    "  const server = createServer();",
    "  const transport = new StreamableHTTPServerTransport({",
    "    sessionIdGenerator: undefined,",
    "    enableDnsRebindingProtection: true,",
    "    allowedHosts: allowedHostList,",
    "  });",
    '  res.on("close", () => {',
    "    void transport.close();",
    "    void server.close();",
    "  });",
    "  await server.connect(transport);",
    "  await transport.handleRequest(req, res);",
    "}).listen(port, () => {",
    `  console.error(${JSON.stringify(name + " MCP server on http://localhost:")} + port + "/mcp");`,
    "});",
    "",
  ].join("\n");
}

export function envExample(baseUrl: string, schemes: SecurityScheme[]): string {
  const lines = ["# Environment for the generated MCP server.", ""];
  lines.push("# Base URL of the upstream API.");
  lines.push(`API_BASE_URL=${baseUrl || "https://api.example.com"}`);
  if (schemes.length > 0) {
    lines.push("");
    lines.push("# Credentials (read at runtime; never commit real values).");
    for (const s of schemes) {
      for (const v of s.envVars) lines.push(`${v}=`);
    }
  }
  lines.push("");
  return lines.join("\n");
}

export function serverJson(name: string, version: string, description: string): string {
  // Minimal MCP Registry-style manifest the user can adapt before publishing.
  const manifest = {
    $schema: "https://static.modelcontextprotocol.io/schemas/2025-09-29/server.schema.json",
    name: `io.github.OWNER/${name}`,
    description,
    version,
    packages: [
      {
        registryType: "npm",
        identifier: name,
        version,
        transport: { type: "stdio" },
      },
    ],
  };
  return JSON.stringify(manifest, null, 2) + "\n";
}

export function clientConfigMd(name: string): string {
  return [
    "# Add this server to an MCP client",
    "",
    "After `npm install && npm run build`, register the server.",
    "",
    "## Claude Desktop / Claude Code (`mcp.json` or `claude_desktop_config.json`)",
    "",
    "```json",
    "{",
    '  "mcpServers": {',
    `    "${name}": {`,
    '      "command": "node",',
    `      "args": ["./dist/index.js"],`,
    '      "env": {',
    '        "API_BASE_URL": "https://api.example.com"',
    "      }",
    "    }",
    "  }",
    "}",
    "```",
    "",
    "## Cursor (`.cursor/mcp.json`) and Codex use the same `mcpServers` shape.",
    "",
    "Set any required credential env vars (see `.env.example`).",
    "",
  ].join("\n");
}

export interface ReadmeData {
  serverName: string;
  apiTitle: string;
  toolCount: number;
  schemes: SecurityScheme[];
  transport: Transport;
}

export function readmeMd(data: ReadmeData): string {
  const envLines = data.schemes.flatMap((s) => s.envVars).map((v) => "- `" + v + "`");
  const lines = [
    `# ${data.serverName}`,
    "",
    `An MCP server for **${data.apiTitle}**, generated by [${GENERATOR_NAME}](https://github.com/krishgok/mcp-api-translator).`,
    `It exposes ${data.toolCount} tool(s) that call the upstream API directly.`,
    "",
    "## Quickstart",
    "",
    "```bash",
    "npm install",
    "npm run build",
    "cp .env.example .env   # then fill in values",
    "npm start              # runs over stdio",
    "```",
    "",
    "## Configuration",
    "",
    "- `API_BASE_URL` — base URL of the upstream API.",
    ...(envLines.length > 0 ? ["", "Credentials:", ...envLines] : []),
    "",
    "## Connecting a client",
    "",
    "See `client-config.md` for ready-to-paste Claude / Cursor / Codex config.",
    "",
    ...(data.transport === "http" || data.transport === "both"
      ? [
          "## HTTP transport",
          "",
          "```bash",
          "npm run start:http   # Streamable HTTP on PORT (default 3000) at /mcp",
          "```",
          "",
        ]
      : []),
    "## Publishing for discovery",
    "",
    "Edit `server.json` (set your owner/namespace) and publish to the official MCP Registry",
    "so AI clients can discover this server.",
    "",
    "## Regenerating / extending",
    "",
    "This project carries a `.mcp-translator.json` manifest. Point mcp-api-translator's",
    "`extend_mcp_server` tool at this directory with another spec to add more tools; your",
    "hand-edited tool files are preserved.",
    "",
  ];
  return lines.join("\n");
}

export function dockerfile(): string {
  return [
    "# Build stage: needs devDependencies (typescript) to compile.",
    "FROM node:20-alpine AS build",
    "WORKDIR /app",
    "COPY package*.json ./",
    "RUN npm install",
    "COPY . .",
    "RUN npm run build",
    "",
    "# Runtime stage: production deps only, runs as the non-root 'node' user.",
    "FROM node:20-alpine",
    "ENV NODE_ENV=production",
    "WORKDIR /app",
    "COPY package*.json ./",
    "RUN npm install --omit=dev && npm cache clean --force",
    "COPY --from=build /app/dist ./dist",
    "USER node",
    'CMD ["node", "dist/index.js"]',
    "",
  ].join("\n");
}
