# Smoke test for the FastMCP-flavored generated output: install the project generated by
# `npm run e2e:python` (build/e2e-python-out-fastmcp), then run this script. It drives the
# generated server through FastMCP's in-memory client and asserts the raw JSON-Schema tool
# inputs survived verbatim — py_compile alone can't catch a wrong FastMCP API surface.
import asyncio
import json
import pathlib
import sys

root = pathlib.Path(__file__).resolve().parent.parent
project = root / "build" / "e2e-python-out-fastmcp"
sys.path.insert(0, str(project))

from e2e_fastmcp_py.server import server  # noqa: E402
from fastmcp import Client  # noqa: E402


async def main():
    tools_json = json.loads((project / "e2e_fastmcp_py" / "tools.json").read_text())
    expected = {t["name"]: t["inputSchema"] for t in tools_json}

    async with Client(server) as client:
        tools = await client.list_tools()
        names = sorted(t.name for t in tools)
        assert names == sorted(expected), f"tool names diverged: {names}"
        for t in tools:
            assert t.inputSchema == expected[t.name], f"schema for {t.name} was not preserved"
    print(f"fastmcp-smoke OK — {len(tools)} tools served, raw schemas preserved verbatim")


asyncio.run(main())
